---
title: "Untitled"
author: "Menghong Han"
date: "2020/5/31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r pressure, echo=FALSE}
rm(list = ls())
gc()
```


```{r}
library(readxl)
library(dplyr)
#install.packages('dummies')
library(dummies)
library(tidyr)
```


```{r}
# Load data
Covid19 <- read_xlsx("/Users/tmh/Desktop/healthcare/covid-19/Covid19_SourceFile.xlsx")
ICD10 <- read_xlsx("/Users/tmh/Desktop/healthcare/covid-19/ICD10_Dx_TaxonomyTree.xlsx", sheet = "ICD10TaxonomyTree")
ICD10_DGL_3 = ICD10 %>% select(c("ICD10 Dx Code", "DGL_3_Extend"))
```


```{r}
head(Covid19)
```

```{r}
head(ICD10_DGL_3)
```


```{r}
# Map age variable
Covid19_RecodeAge <- Covid19 %>% mutate(RecodeAge = case_when(AgeCode %in% c(1,2) ~ "RefUnder18", AgeCode %in% c(3,4,5,6) ~ "Age_18_39", AgeCode %in% c(7,8,9,10) ~ "Age_40_49", AgeCode %in% c(11,12) ~ "Age_60_69", AgeCode == 13 ~ "Age_70_74", AgeCode == 14 ~ "Age_75_99", AgeCode == 0 ~ "RefUnder18"))

table = dummy(Covid19_RecodeAge$RecodeAge)
```

```{r}
table_name = c("Age_18_39", "Age_40_49", "Age_60_69", "Age_70_74", "Age_75_99", "RefUnder18")
colnames(table) = table_name
Covid_DumAge = as.data.frame(cbind(PatientID = Covid19$`Patient ID`, Mortality = Covid19$`Mortality (1= death)`, table))
head(Covid_DumAge)
```

```{r}
# Map sex variable
Covid19_RecodeAge_Sex <- Covid19_RecodeAge %>% mutate(Gender_Male = case_when(SexCode == 2 | SexCode == 0 ~ 0, SexCode ==1 ~ 1))
head(Covid19_RecodeAge_Sex)
```

```{r}
Covid_DumAge_Sex = cbind(Covid_DumAge, Gender_Male = Covid19_RecodeAge_Sex$Gender_Male)
head(Covid_DumAge_Sex)
```

```{r}
# Map DX1 to DX20 to DGL_3_Extend
# Step 1: transform the data into long format
Covid19_long = gather(Covid19, Type, ICD10_Dx_Code,DX1:DX20, factor_key = TRUE)
head(Covid19_long)
```


```{r}
unique(ICD10$DGL_3_Extend)
```
```{r}
# Step2: join Covid19_long_no_NA with ICD10
Covid19_ICD10 = merge(Covid19_long, ICD10_DGL_3, by.x ="ICD10_Dx_Code", by.y = "ICD10 Dx Code")
head(Covid19_ICD10)
```


```{r}
table3 = dummy(Covid19_ICD10$DGL_3_Extend)
```
```{r}
table_final = as.data.frame(cbind(PatientID = Covid19_ICD10$`Patient ID`, table3))%>% arrange(PatientID)%>% group_by(PatientID)
```

```{r}
table_final5 = merge(Covid_DumAge_Sex,table_final, by = "PatientID")
dim(table_final5)
```

head(table_final5)
