---
title: "Untitled"
author: "Jinman Rong"
date: "5/26/2020"
output: html_document
---

```{r}
library(dplyr)
library(data.table)
library(tidyverse)
library(readxl)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ICD10_BCOL <- read.csv("~/Desktop/MedBlob/ICD10_BCOL.csv")
head(ICD10_BCOL)

final_result <- read.csv("~/Downloads/final result (2).csv")
final_result <- final_result %>% select(-c("Mortality..1..death.","X"))
head(final_result)
```

```{r}
heart<-(grep("*heart",ICD10_BCOL$ICD10.Dx.Code.Desc,value=T))
heart2<-(grep("*Heart",ICD10_BCOL$ICD10.Dx.Code.Desc,value=T))
t1 = as.data.table(levels(as.factor(heart)))
t2 = as.data.table(levels(as.factor(heart2)))
hearticd10desc = rbind(t1,t2)
ICD10_BCOL[ICD10_BCOL$ICD10.Dx.Code.Desc == levels(as.factor(heart))|ICD10_BCOL$ICD10.Dx.Code.Desc == levels(as.factor(heart2)),]
```

```{r}
ICD10 <- read_xlsx("/Users/tmh/Desktop/MedBlob/riskscorelogisticsmodelanddatasets/covid-19/ICD10_Dx_TaxonomyTree.xlsx", sheet = "ICD10TaxonomyTree")

table_desc_dgl3 <- merge(hearticd10desc,ICD10, by.x = "V1", by.y = "ICD10 Dx Code Desc") %>% select(c("V1", "DGL_3_Extend"))
```
```{r}

table_desc_dgl3_unique = as.data.table(levels(as.factor(table_desc_dgl3$DGL_3_Extend)))
dlg3_heart_disease = table_desc_dgl3_unique[1:8,]

```

```{r}
X_predictors <-final_result %>% select(-c("CVASC_Cardiac_A","CVASC_Cardiac_B","CVASC_Complication_B","CVASC_Heart_Rhythm_A","CVASC_Other_Nos_A","CVASC_Other_Nos_B","CVASC_Status_A","CVASC_Status_B"))
ncol(X_predictors)
```
```{r}
Records <- final_result[final_result$CVASC_Cardiac_A==1|final_result$CVASC_Cardiac_B==1|final_result$CVASC_Complication_B==1|final_result$CVASC_Heart_Rhythm_A==1|final_result$CVASC_Other_Nos_A==1|final_result$CVASC_Other_Nos_B==1|final_result$CVASC_Status_A==1|final_result$CVASC_Status_B==1,] # 得病

Records_heart_disease <-Records %>% mutate(y = 1) # 产生得病y
nrow(Records_heart_disease)

Healthy_Records <- final_result[-Records_heart_disease$Patient.ID,] %>% mutate(y = 0)

table = rbind(Healthy_Records,Records_heart_disease)

final_table <-table%>% select(-c("CVASC_Cardiac_A","CVASC_Cardiac_B","CVASC_Complication_B","CVASC_Heart_Rhythm_A","CVASC_Other_Nos_A","CVASC_Other_Nos_B","CVASC_Status_A","CVASC_Status_B")) # predictors

colnames(final_table)

write.csv(final_table,"final_table.csv")
```

```{r}
RAMDOM_SEED = 22
sample_split = function(final_table, y, p = 0.8, v = 0.1) {
  len = length(unlist(final_table[,1]))
  
  # Generate index for spliting original dataset
  set.seed(RAMDOM_SEED)
  train_index = sample(1:len, round(len*p, 0))
  val_index = sample((1:len)[-train_index], round(len*v, 0))
  test_index = (1:len)[-c(train_index, val_index)]
  cat(sprintf('[Description]\n  Number of sample: %7s\n  Training set: %11s\n  Validation set: %8s\n  Test set: %15s', 
              len, length(train_index), length(val_index), length(test_index)))
  
  # Generate training set, validation set and testing set
  X = colnames(final_table)[colnames(final_table) != y]
  train_x = final_table[train_index, X]
  train_y = final_table[train_index, y]
  val_x = final_table[val_index, X]
  val_y = final_table[val_index, y]
  test_x = final_table[test_index, X]
  test_y = final_table[test_index, y]
  
  dataset_list = list(train_x=train_x, train_y=train_y, val_x=val_x, 
                      val_y=val_y, test_x=test_x, test_y=test_y, 
                      train_n=length(train_index), val_n=length(val_index), test_n=length(test_index))
}
```

```{r}
sample        = sample_split(final_table,'y')
```

```{r}
#mylogit <- glm(sample$train_y ~ ., data = sample$train_x, family = "binomial")

```

