```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r pressure, echo=FALSE}
rm(list = ls())
gc()
```


```{r}
# Include Foreign Package To Read SAS Transport Files
library(foreign)
library(dummies)
library(tidyr)
library(dplyr)
```

```{r}
# Create Temporary File To Store Downloaded SAS Transport Files
tf <- tempfile()
```

#2015-2016
#Demographic Data 

```{r}
# Download NHANES 2015-2016 Demographic Data 
download.file("https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/DEMO_I.XPT", tf, mode="wb")
# Create Data Frame From Temporary File & Keep Variables Of Interest                                              
DEMO <- read.xport(tf)[,c("SEQN","RIAGENDR","RIDAGEYR","RIDRETH3","DMDEDUC2","DMDMARTL")]

DEMO$RIAGENDR <- case_when(DEMO$RIAGENDR==1~1, DEMO$RIAGENDR==2~0)
DEMO$RIAGENDR <- as.factor(DEMO$RIAGENDR)

DEMO$Race <- factor(DEMO$RIDRETH3, labels=c("Mexican American","Other Hispanic","Non-Hispanic White","Non-Hispanic Black","6	Non-Hispanic Asian","Other Race - Including Multi-Racial"))
Race <- dummy(DEMO$Race)


DEMO$DMDEDUC2 <- case_when((DEMO$DMDEDUC2 == 1 | DEMO$DMDEDUC2 == 2)~0,(DEMO$DMDEDUC2 == 3 | DEMO$DMDEDUC2 == 4 | DEMO$DMDEDUC2 == 5)~1)
DEMO$DMDEDUC2 <- as.factor(DEMO$DMDEDUC2)


DEMO$DMDMARTL <- case_when((DEMO$DMDMARTL == 1) ~ 1,(DEMO$DMDMARTL == 2 | DEMO$DMDMARTL == 3 | DEMO$DMDMARTL == 4)~0, (DEMO$DMDMARTL == 5 | DEMO$DMDMARTL == 6)~2)
DEMO$DMDMARTL <- as.factor(DEMO$DMDMARTL)

demo <-as.data.frame(cbind(SEQN=DEMO$SEQN,Gender=DEMO$RIAGENDR,Age=DEMO$RIDAGEYR,Race))
demo$Gender <- case_when(demo$Gender==1~1, demo$Gender==2~0)
demo$Gender <- as.factor(demo$Gender)
nrow(demo)
```




#Diabetes, heart disease, family history, health condition

```{r}
# Download NHANES 2015-2016 Medical Conditions Data 
download.file("https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/MCQ_I.XPT", tf, mode="wb")
# Create Data Frame From Temporary File & Keep Variables Of Interest                                              
medic <- read.xport(tf)[,c("SEQN","MCQ160C","MCQ160B","MCQ160E","MCQ300A","MCQ300B","MCQ300C","MCQ365A","MCQ365B","MCQ365C","MCQ365D","MCQ160F")]
medic[is.na(medic)]<-0


medic$MCQ160C = case_when(medic$MCQ160C == 1 ~ 1, medic$MCQ160C == 2 ~ 0)
medic$MCQ160C = as.factor(medic$MCQ160C)

medic$MCQ160B = case_when(medic$MCQ160B == 1 ~ 1, medic$MCQ160B == 2 ~ 0)
medic$MCQ160B = as.factor(medic$MCQ160B)

medic$MCQ160E = case_when(medic$MCQ160E == 1 ~ 1, medic$MCQ160E == 2 ~ 0)
medic$MCQ160E = as.factor(medic$MCQ160E)



medic$MCQ300A = case_when(medic$MCQ300A == 1 ~ 1, medic$MCQ300A == 2 ~ 0)
medic$MCQ300A = as.factor(medic$MCQ300A)

medic$MCQ300B = case_when(medic$MCQ300B == 1 ~ 1, medic$MCQ300B == 2 ~ 0)
medic$MCQ300B = as.factor(medic$MCQ300B)

medic$MCQ300C = case_when(medic$MCQ300C == 1 ~ 1, medic$MCQ300C == 2 ~ 0)
medic$MCQ300C = as.factor(medic$MCQ300C)

medic$MCQ365A = case_when(medic$MCQ365A == 1 ~ 1, medic$MCQ365A == 2 ~ 0)
medic$MCQ365A = as.factor(medic$MCQ365A)

medic$MCQ365B = case_when(medic$MCQ365B == 1 ~ 1, medic$MCQ365B == 2 ~ 0)
medic$MCQ365B = as.factor(medic$MCQ365B)


medic$MCQ365C = case_when(medic$MCQ365C == 1 ~ 1, medic$MCQ365C == 2 ~ 0)
medic$MCQ365C = as.factor(medic$MCQ365C)

medic$MCQ365D = case_when(medic$MCQ365D == 1 ~ 1, medic$MCQ365D == 2 ~ 0)
medic$MCQ365D = as.factor(medic$MCQ365D)


med <- medic %>% select(-"MCQ160F") %>% drop_na()

```




#ALcohol

```{r}
# Download NHANES 2015-2016 ALcohol Data 
download.file("https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/ALQ_I.XPT", tf, mode="wb")
# Create Data Frame From Temporary File & Keep Variables Of Interest                                              
alcohol <- read.xport(tf)[,c("SEQN","ALQ101")]
alcohol$ALQ101<-case_when(alcohol$ALQ101==1 ~ 1, alcohol$ALQ101==2 ~ 0)
alcohol$ALQ101<- as.factor(alcohol$ALQ101)
alcohol<-na.omit(alcohol)
```

#Smoke

```{r}
# Download NHANES 2015-2016 Smoke Data 
download.file("https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/SMQ_I.XPT", tf, mode="wb")
# Create Data Frame From Temporary File & Keep Variables Of Interest                                              
smoke<- read.xport(tf)[,c("SEQN","SMQ020")]
smoke$SMQ020<- case_when(smoke$SMQ020==1 ~ 1, smoke$SMQ020==2 ~ 0)
smoke$SMQ020<- as.factor(smoke$SMQ020)
smoke<- na.omit(smoke)
```



#BMI

```{r}
# Download NHANES 2015-2016 BMI Data 
download.file("https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/BMX_I.XPT", tf, mode="wb")
# Create Data Frame From Temporary File & Keep Variables Of Interest                                              
BMI <- read.xport(tf)[,c("SEQN","BMXBMI")]
nrow(BMI)
```

#Blood Pressure

```{r}
# Download NHANES 2015-2016 Blood Pressure Data 
download.file("https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/BPX_I.XPT", tf, mode="wb")
# Create Data Frame From Temporary File & Keep Variables Of Interest                                              
bp <- read.xport(tf)[,c("SEQN","BPXPLS","BPXSY1","BPXSY2","BPXSY3","BPXSY4","BPXDI1","BPXDI2","BPXDI3","BPXDI4")]
bp[is.na(bp)]<-0
bp$avgSY <- apply(bp[,3:6], 1, mean)
bp$avgDI <- apply(bp[,7:10], 1, mean)
bp<-bp[,c("SEQN","BPXPLS","avgSY","avgDI")]
nrow(bp)
```

#Cholesterol - Total

```{r}

# Download NHANES 2015-2016 Cholesterol - Total Data 
download.file("https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/TCHOL_I.XPT", tf, mode="wb")
# Create Data Frame From Temporary File & Keep Variables Of Interest                                              
tc <- read.xport(tf)[,c("SEQN","LBDTCSI")]
```

#Cholesterol - High-Density Lipoprotein (HDL)

```{r}
# Download NHANES 2015-2016 Cholesterol - High-Density Lipoprotein (HDL) Data 
download.file("https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/HDL_I.XPT", tf, mode="wb")
# Create Data Frame From Temporary File & Keep Variables Of Interest                                              
hdl <- read.xport(tf)[,c("SEQN","LBDHDDSI")]
#hdl<-na.omit(hdl)
tc_hdl <- merge(tc,hdl, by = "SEQN")
tc_hdl<-mutate(tc_hdl,AI=tc_hdl$LBDTCSI/tc_hdl$LBDHDDSI)
AI<-tc_hdl[,c(1,4)]
```



# Diabetes

```{r}
# Download NHANES 2015-2016 Diabetes
download.file("https://wwwn.cdc.gov/Nchs/Nhanes/2015-2016/DIQ_I.XPT", tf, mode="wb")
# Create Data Frame From Temporary File & Keep Variables Of Interest                                              
dia <- read.xport(tf)[,c("SEQN","DIQ010")]
dia$DIQ010<- case_when(dia$DIQ010==1 ~ 1, dia$DIQ010==2 ~ 0)
dia$DIQ010<- as.factor(dia$DIQ010)
dia<- na.omit(dia)
```



# Merge all tables
```{r}
alltable<-Reduce(function(x,y) merge(x = x, y = y, by = "SEQN"), 
                 list(demo,BMI,bp,med, tc,AI, alcohol,smoke,dia))

```

# Tareget
```{r}
stroke <- medic[medic$MCQ160F==1,] # have stroke

Records_stroke <-stroke %>% mutate(y = 1) 
Records_stroke<-Records_stroke[c("SEQN","y")]
nrow(Records_stroke)

Healthy_Records <- alltable[-Records_stroke$SEQN,] %>% mutate(y = 0)
Healthy_Records <-Healthy_Records[c("SEQN","y")]
table = rbind(Healthy_Records,Records_stroke)
table<-table[c("SEQN","y")]

table_final = merge(alltable,table, by = "SEQN")
table_final[is.na(table_final)]<-0
nrow(table_final)

```






```{r}

# normalize input variables
colnames(table_final)

selected<- table_final[,c(3,10:13,24:25)]
unse<-table_final[,-c(3,10:13,24:25)]
normalization<-function(x){
  return((x-min(x))/(max(x)-min(x)))}
norm<-normalization(selected)

table_final1<-cbind(unse[,1:21],norm,y=unse$y)
colnames(table_final1) = c("SEQN","Gender","Mexican_American","Other_Hispanic","NonHispanic_White","NonHispanic_Black",  "NonHispanic_Asian", "RaceOther Race - Including Multi-Racial","Edu","Widowed_Divorced_Separated","Married","Diabetes","Worried_anxious_daily","Worried_anxious_weekly","Worried_anxious_monthly","Worried_anxious_A_few_times_a_year","Worried_anxious_never","Depressed_daily","Depresseds_weekly","Depressed_monthly","Depressed_A_few_times_a_year","Depressed_never","serious_difficulty_walking","Asthma","Arthritis","Coronary_heart_disease","Congestive_heart_failure","Heart_attack","Stroke","Close_Relative_Heart_Attack","Close_Relative_Asthma","Close_Relative_Diabetes","Overweight","Lack_Exercise","High_Salt","Hight_Fat_Calories","More_emergency_room_visits_or_overnight_hospital_stays","Exposure_to_secondhand_smoke","Smoked_at_least_100_cigarettes_in_life","Ever_smoked_a_cigar_even_one_time","Ever_used_an_ecigarette","Ever_used_smokeless_tobacco","Experience_confusion_or_memory_problems","Walking_up_ten_steps_difficulty_No","Walking_up_ten_steps_difficulty_Some","Walking_up_ten_steps_difficulty_Much","Walking_up_ten_steps_difficulty_Unable","Limitations_keeping_you_from_working","Going_out_to_movies_events_difficulty_No","Going_out_to_movies_events_difficulty_Some","Going_out_to_movies_events_difficulty_Much","Going_out_to_movies_events_difficulty_Unable","Attending_social_event_difficulty_No","Attending_social_event_difficulty_Some","Attending_social_event_difficulty_Much","Attending_social_event_difficulty_Unable","Leisure_activity_at_home_difficulty_NO","Leisure_activity_at_home_difficulty_Some","Leisure_activity_at_home_difficulty_Much","Leisure_activity_at_home_difficulty_Unable","Age","y") 
write.csv(table_final1,"/Users/tmh/Desktop/MedBlob/stroke(normalized).csv")


```

